### ISSUE TITLE
conflict with conky

### ISSUE THREAD

**Issue by vgay** [l3ib/nitrogen#90] opened 2016-12-26 17:39 UTC
using archlinux, openbox, nitrogen 1.6.0-2, 2 monitors and conky. Nitrogen works fine when conky IS NOT running but does not show my 2 monitors otherwise: The error message when running from command line:
`UNKNOWN ROOT WINDOW TYPE DETECTED, will attempt to set via normal X procedure`

**Comment by daf** [comment] 2017-01-01 16:15
Hi @vgay , this is fixed in 9821adf08bd77afdf9b96099a05b966822986d40.  I'm trying to get one or two more issues fixed up before I release 1.6.1.

**Comment by daf** [comment] 2017-01-01 16:16
(dupe of #88 / #86 / #76)

**Closed by daf** 2017-01-01 16:15 UTC
